---

- hosts: all
  become: true
  tasks:

  - name: comment out the swap image from fstab
    replace:
      path: /etc/fstab
      regexp: '^/swap.img'
      replace: '#/swap.img'
  
  - name: rebooting all nodes
    reboot:
