---

- hosts: all
  become: true
  tasks:

  - name: copyng modules needed for the container
    copy:
      src: '{{ conf_path }}/k8s-modules.conf'
      dest: /etc/modules-load.d/k8s.conf
      owner: root
      group: root
      mode: u=rw,g=r,o=r
  - name: copyng low level network config needed for the container
    copy:
      src: '{{ conf_path }}/k8s-net.conf'
      dest: /etc/sysctl.d/k8s.conf
      owner: root
      group: root
      mode: u=rw,g=r,o=r
  - name: Apply sysctl params without reboot
    shell: sysctl --system
