---

- hosts: all
  become: true
  tasks:

  - name: Creating the default configuration file for containerd
    shell: containerd config default | tee /etc/containerd/config.toml
  - name: enable SystemdCgroup for containerd
    replace:
      path: /etc/containerd/config.toml
      regexp: 'SystemdCgroup = false'
      replace: 'SystemdCgroup = true'
  - name: containerd restart
    systemd:
      state: restarted
      name: containerd
